services:
  shopapi:
    image: shop-api-dev:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8015:8080"
    container_name: shop-api-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      carenest-network:
        ipv4_address: 192.168.0.18

networks:
  carenest-network:
    external: true
